
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ProgJazz and Johnny 28
 */

import java.io.*;
import java.util.StringTokenizer;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class ConfirmSlip extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmSlip
     */
    public ConfirmSlip(CustomerDetails obj) {
        initComponents();
        Icon img=new ImageIcon("Images\\Bigcontentmediamainpix_700x396.jpg");
        jLabel27.setIcon(img);
        jLabel22.setText(obj.name);
        jLabel23.setText(obj.eMail);
        jLabel24.setText(obj.pass);
        jLabel11.setText(obj.spice);
        jLabel12.setText(obj.silk);
        jLabel5.setText(obj.source);
        jLabel21.setText(obj.sourceTime);
        jLabel20.setText(obj.desTime);
        jLabel19.setText(String.valueOf(obj.d) + " OCT");
        jLabel18.setText(String.valueOf(obj.a) + " OCT");
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("Files/PassengerDatabase.csv"));
            String line;
            while ((line = br.readLine()) != null) {
                StringTokenizer str = new StringTokenizer(line, "|");
                jLabel26.setText(String.valueOf((Integer.parseInt(str.nextToken()))));
            }
        }
        catch(IOException e) {
            System.out.println("File cannot be read...");
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Booking Confirmation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 300, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("N");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(230, 110, 316, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 70, 50, 25);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("N");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(230, 190, 316, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Email Id:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 110, 70, 25);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 51));
        jLabel25.setText("Number of Passenger:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(67, 188, 160, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Booking Id:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 150, 90, 25);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("N");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(230, 150, 316, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(164, 293, 77, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("SilkAir:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 250, 60, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Destination:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 290, 90, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Singapore");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 290, 77, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("SpiceJet:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(67, 250, 70, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Source:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(67, 293, 60, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("1");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(164, 250, 70, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("2");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 250, 60, 25);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Time:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(330, 330, 40, 25);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Dep. Date: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(67, 336, 80, 25);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Arrival Date: ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(67, 372, 90, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("Time:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(329, 372, 40, 25);

        jLabel17.setFont(new java.awt.Font("Showcard Gothic", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Thank You");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(250, 410, 100, 25);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("1");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(164, 372, 77, 25);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("1");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(164, 336, 77, 25);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("2");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(430, 370, 130, 25);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("2");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(430, 330, 77, 25);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("N");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(230, 70, 316, 25);
        getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 0, 580, 0);
        getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 580, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
