
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ProgJazz and Johnny 28
 */
public class CustomerDetails extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLogin
     * @param objdisplay
     * @param objsearch
     */
    FlightList objdisplay;
    
    public String source, sourceTime, dest, spice, silk, pass, name, eMail, desTime;
    public int d, a;
    public CustomerDetails(FlightList objdisplay, SearchFlight objsearch) {
        initComponents();
        this.objdisplay=objdisplay;
        Icon img1=new ImageIcon("Images\\interior.jpg");
        jLabel6.setIcon(img1);
        
        sourceTime=(String) objdisplay.jTable1.getModel().getValueAt(objdisplay.selRow, 0);
        source=(String) objsearch.jComboBox1.getSelectedItem();
        spice=((String) objdisplay.jTable1.getModel().getValueAt(objdisplay.selRow, 1));
        silk=((String) objdisplay.jTable1.getModel().getValueAt(objdisplay.selRow, 6));
        desTime=((String) objdisplay.jTable1.getModel().getValueAt(objdisplay.selRow, 7));
        pass=objsearch.jComboBox2.getSelectedItem().toString();
        jLabel8.setText("From: "+source+" At: "+sourceTime);
        d = Integer.parseInt(objsearch.jComboBox5.getSelectedItem().toString());
        if (sourceTime.contains("PM") && desTime.contains("AM")) {
            a = d + 1;
        }
        String th="th";
        int d1=d%10;
        if (d1==1)
            th="st";
        else if(d1==2)
            th="nd";
        else if(d1==3)
            th="rd";
        jLabel9.setText("Date of Departure: "+d+""+th+" Oct 2015");
        jLabel10.setText("SpiceJet: "+spice);
        jLabel11.setText("SilkAir: "+silk);
        jLabel12.setText("No. of passenger: "+pass);
        jLabel13.setText("Duration: "+objdisplay.jTable1.getModel().getValueAt(objdisplay.selRow, 8));
        jButton1.addMouseListener(new MouseAdapter() {
             @Override
            public void mouseEntered(MouseEvent e) {
                jButton1.setFont(jButton1.getFont().deriveFont(Font.BOLD));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                 jButton1.setFont(jButton1.getFont().deriveFont(Font.PLAIN));
            }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Enter Details:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 50, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Email Id:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Flight Details:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 180, 100, 17);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 130, 299, 23);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 80, 299, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 180, 299, 24);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 210, 299, 24);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("3");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 240, 299, 24);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("4");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 270, 299, 24);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("5");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(140, 300, 299, 24);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("6");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(140, 330, 300, 24);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 370, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Go back");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 20, 60, 40);

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 570, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DisplayManager obj = new DisplayManager();
        name = this.jTextField3.getText();
        eMail = this.jTextField1.getText();
        
        if (name.equals("") || eMail.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter Name and Email Id");
        }
        else if (eMail.contains("@") == false) {
            JOptionPane.showMessageDialog(null, "Please enter valid Email Id");
        }
        else {
            BookingManager bm = new BookingManager(spice, name, d, Integer.parseInt(pass));
            int seat = Integer.parseInt(pass);
            bm.bookTicket(seat);
            obj.displayTicket(this);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        objdisplay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jLabel5.setFont(jLabel5.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        jLabel5.setFont(jLabel5.getFont().deriveFont(Font.PLAIN));
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
